app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    with app.app_context():
        from .routes.home import index_route
        from .routes.produtos import product_route
        app.register_blueprint(index_route)
        app.register_blueprint(product_route, url_prefix='/produtos')

    return app

app/routes/home.py
from flask import Blueprint, render_template

index_route = Blueprint('index', __name__)

@index_route.route('/')
def home():
    return render_template('index.html')

app/routes/produtos.py
from flask import Blueprint, render_template, request
from database.produto import PRODUTOS

product_route = Blueprint('produto', __name__)

'''
Rotas
    - /produtos/ (GET) - listar os produtos
    - /produtos/ (POST) - inserir o produto no servidor
    - /produtos/new (GET) - formulario para inserir produtos
    - /produtos/<id> (GET) - obter os dados de um produto
    - /produtos/<id>/edit/ (GET) - formulario para editar um produto 
    - /produtos/<id>/update (PUT)- atualizar dados do produto
    - /produtos/<id>/delete (DELETE) - deleta os registros do produto
'''

@product_route.route('/')
def listar_produtos():
    return render_template('listar_produtos.html', produtos=PRODUTOS)

@product_route.route('/', methods=['POST'])
def inserir_produtos():
    # append na lista de um novo dict
    data = request.json

    new_product = {
        'id': len(PRODUTOS) + 1,
        'nome': data['nome'],
        'estoque': data['estoque'],
        'preco': data['preco']
    }

    PRODUTOS.append(new_product)

    return render_template('item_produto.html', produto=new_product)


@product_route.route('/new')
def novo_produto():
    return render_template('novo_produto.html')

@product_route.route('/<int:product_id>')
def detalhe_produto(product_id):
    return render_template('detalhe_produto.html')

@product_route.route('/<int:product_id>/edit')
def editar_produto(product_id):
    produto = None

    for p in PRODUTOS:
        if p['id'] == product_id:
            produto = p

    return render_template('novo_produto.html', produto=produto)

@product_route.route('/<int:product_id>/update', methods=['PUT'])
def update_produto(product_id):
    produto_editado = None
    data = request.json

    for p in PRODUTOS:
        if p['id'] == product_id:
            p['nome'] = data['nome']
            p['estoque'] = data['estoque']
            p['preco'] = data['preco']

            produto_editado = p

    return render_template('item_produto.html', produto=produto_editado)

@product_route.route('/<int:product_id>/delete', methods=['DELETE'])
def deletar_produto(product_id):
    global PRODUTOS

    PRODUTOS = [ p for p in PRODUTOS if p['id'] != product_id ]
    
    return {'deleted': 'ok'}

app/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estoque</title>
    <link rel="shortcut icon" href="./static/boxes_3638933.png" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>

    <div class="container">
      <h1 class="text-center">Gestao de produtos</h1>

      <!-- Formulario add produto -->
      <div id="form-produto"
        c-container="{{  url_for('produto.novo_produto')  }}"></div>

      <hr>

      <!--Lista de produtos -->
      <h2>Lista de produtos</h2>
      <div c-container="{{ url_for('produto.listar_produtos') }}"></div>

    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{  url_for('static', filename='cru.js')  }}"></script>
  </body>
</html>

app/templates/item_produto.html
<tr id="produto-{{produto.id}}">
    <th scope="row">{{ produto.id }}</th>
    <td>{{ produto.nome }}</td>
    <td>{{ produto.estoque }} kg</td>
    <td>R${{ produto.preco }}</td>
    <td>
        <button class="btn btn-primary" 
            c-get="{{ url_for('produto.editar_produto', product_id=produto.id) }}"
            c-target="#form-produto">Editar</button>
        <button class="btn btn-danger" 
            c-delete="{{ url_for('produto.deletar_produto', product_id=produto.id) }}"
            c-remove-closest="tr">Deletar</button>
    </td>
</tr>

app/templates/listar_produtos.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Produto</th>
        <th scope="col">Kg em estoque</th>
        <th scope="col">Preco p/ kg</th>
      </tr>
    </thead>
    <tbody id="lista_produtos">

        {%  for produto in produtos  %}
          {%  include 'item_produto.html'  %}
        {%  endfor  %}
        
    </tbody>
  </table>

app/templates/novo_produto.html
<form class="c-form" 
    {% if produto %}
        action="{{ url_for('produto.update_produto', product_id=produto.id) }}"
    {% else %}
        action="{{ url_for('produto.inserir_produtos') }}"
    {% endif %}

    method="{% if produto %}PUT{% else %}POST{% endif %}"

    {% if produto %}
        c-swap="#produto-{{produto.id}}"
    {% else %}
        c-append="#lista_produtos"
    {% endif %}

    c-reload-container="true">
            <!-- Nome do Produto -->
            <div class="mb-3">
                <label for="nome" class="form-label">Nome do Produto</label>
                <input type="text" class="form-control" name="nome" {% if produto%}value="{{produto.nome}}"{% endif%} placeholder="Digite o nome do produto" required   >
            </div>

            <!-- Quantidade em Kg -->
            <div class="mb-3">
                <label for="quantidade" class="form-label">Quantidade em Kg</label>
                <input type="number" step="0.001" class="form-control" name="estoque" {% if produto%}value="{{produto.estoque}}"{% endif%} placeholder="Digite a quantidade em Kg" required>
            </div>

            <!-- Preço por Kg -->
            <div class="mb-3">
                <label for="preco" class="form-label">Preço por Kg</label>
                <input type="number" step="0.001" class="form-control"  name="preco" {% if produto%}value="{{produto.preco}}"{% endif%} placeholder="Digite o preço por Kg" required>
            </div>

            <!-- Botão de envio -->
            <button type="submit" class="btn btn-primary">
                {% if produto%}Atualizar{% else%}Inserir Produto{% endif%}</button>
        </form>
 